[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence and Augmented Reality: Building Intelligent AR Systems That Enhance the User Experience"
